export const ENDPOINTS = {
    LOGIN: import.meta.env.VITE_ENDPOINT_LOGIN,
    REGISTER: import.meta.env.VITE_ENDPOINT_REGISTER,
    GOOGLE_CALLBACK: import.meta.env.VITE_ENDPOINT_GOOGLE_CALLBACK,

    ADMIN_COURSE: import.meta.env.VITE_ENDPOINT_ADMIN_COURSE,
    ADMIN_USERS: import.meta.env.VITE_ENDPOINT_ADMIN_USERS,
    ADMIN_CLASS: import.meta.env.VITE_ENDPOINT_ADMIN_CLASS,
    ADMIN_MODULE: import.meta.env.VITE_ENDPOINT_ADMIN_MODULE,

    CHAT: import.meta.env.VITE_ENDPOINT_CHAT,

    COURSES: import.meta.env.VITE_ENDPOINT_COURSES,
    MODULES: import.meta.env.VITE_ENDPOINT_MODULES,

    USERS: import.meta.env.VITE_ENDPOINT_USERS,
    PROFILE: import.meta.env.VITE_ENDPOINT_PROFILE,

    CURATOR_STUDENTS: import.meta.env.VITE_ENDPOINT_CURATOR_STUDENTS,
    CURATOR_COURSES: import.meta.env.VITE_ENDPOINT_CURATOR_COURSES,

    TASK: import.meta.env.VITE_ENDPOINT_TASK,
    ATTACHMENTS: import.meta.env.VITE_ENDPOINT_ATTACHMENTS,

    ANSWERS: import.meta.env.VITE_ENDPOINT_ANSWERS
};